{
 "title": "Network",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_sent_total{nic=\"ASUS_PCE_AC68_802_11ac_Network_Adapter\"}[30s])",
     "legendFormat": "30s"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total{nic=\"ASUS_PCE_AC68_802_11ac_Network_Adapter\"}[40s])",
     "legendFormat": "40s"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total{nic=\"ASUS_PCE_AC68_802_11ac_Network_Adapter\"}[1m])",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{nic=\"ASUS_PCE_AC68_802_11ac_Network_Adapter\"}[30s])",
     "legendFormat": "30s"
    },
    {
     "expr": "rate(windows_net_bytes_received_total{nic=\"ASUS_PCE_AC68_802_11ac_Network_Adapter\"}[40s])",
     "legendFormat": "40s"
    },
    {
     "expr": "rate(windows_net_bytes_received_total{nic=\"ASUS_PCE_AC68_802_11ac_Network_Adapter\"}[1m])",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Packets error",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(windows_net_packets_received_errors_total{nic=\"ASUS_PCE_AC68_802_11ac_Network_Adapter\"}[30s])",
     "legendFormat": "Received packets errors"
    },
    {
     "expr": "rate(windows_net_packets_outbound_errors_total{nic=\"ASUS_PCE_AC68_802_11ac_Network_Adapter\"}[30s])",
     "legendFormat": "Outbound packets errors"
    }
   ]
  }
 ]
}